Release v0.1
pranjalchanda08/rv32i_ISA_emu pull request #14
Opened 2024-10-28 04:39 UTC by pranjalchanda08

2024-10-28 10:03 UTC, akashkollipara commented on LICENSE
> +viable credits to the author of the code. Any breach to the same would be subjected
~viable~ Due

2024-10-28 10:04 UTC, akashkollipara commented on LICENSE
> +to use, modify, merge, publish, distribute, sublicense, and/or sell
allow only till modify

2024-10-28 10:05 UTC, akashkollipara commented on LICENSE
>  Permission is hereby granted, free of charge, to any person obtaining a copy
[x] Remove line 1. Rename the license

2024-10-28 10:06 UTC, akashkollipara commented on inc/ram.h
> +#ifndef _RAM_H_
Start using `#parma once`

2024-10-28 10:10 UTC, akashkollipara requested changes

2024-10-28 10:10 UTC, akashkollipara commented on src/main.c
> +        exit(EXIT_FAILURE);
```C
printf("%s\n", ram ? "RAM Initialized!":"[E: ] Failed to setup RAM");
return ram;
```

2024-10-28 10:10 UTC, akashkollipara commented on src/main.c
>  static void rv32_ram_attach()
Return value.

2024-10-28 12:00 UTC, pranjalchanda08 commented on src/main.c
>  static void rv32_ram_attach()
??

2024-10-28 13:15 UTC, akashkollipara commented on src/main.c
>  static void rv32_ram_attach()
see next comment after this one.

2024-10-28 13:18 UTC, akashkollipara requested changes

2024-10-28 13:18 UTC, akashkollipara commented on src/main.c
> +        exit(EXIT_FAILURE);
handle all error as part of exit routine where you de-init. Avoid exit.

2024-10-28 13:19 UTC, akashkollipara commented on src/main.c
> +        exit(EXIT_FAILURE);
https://github.com/VisorFolks/cc_elf_size/blob/bfe8a0e047e7c919de66e3a0921e9deeb9003ca4/elf_size.c#L272

2024-10-28 13:21 UTC, akashkollipara commented
use valgrind to check memory leaks during failure conditions.
most of the success will not have memory leaks but upon failure, there are.

2024-10-29 09:24 UTC, akashkollipara commented on inc/platmem.h
>  #define RAM_SIZE  _K(16)
you dont need to make function like macro...

```
#define KB *1024
#define SIZE 16KB
```

This works too.

2024-10-29 09:25 UTC, akashkollipara commented on inc/ram.h
>  	uint8_t *mem;     // ram memory of RAM_SIZE
RAM is word addressable not byte addressable.

2024-10-29 09:26 UTC, akashkollipara commented on inc/rv32I_struct.h
> +    void * ram;
`uintptr_t *ram` would be better I suppose.

2024-10-29 10:24 UTC, pranjalchanda08 commented on inc/ram.h
>  	uint8_t *mem;     // ram memory of RAM_SIZE
correct the load store is happening in word addressability only. Check `ram.c`

2024-11-03 03:11 UTC, akashkollipara requested changes

2024-11-03 03:11 UTC, akashkollipara commented on Makefile
> +CC := gcc
try using ccache for faster and efficient builds.
`CC := ccache gcc`
`CXX := ccache g++`

2024-11-03 03:11 UTC, akashkollipara commented on inc/common/main.h
> +#include "rv32i_execute.h"
are you sure you want to use `"..."` instead of `<...>`

2024-11-03 03:11 UTC, akashkollipara commented on inc/common/rv32_err.h
> +    RV32_SUCCESS,
good practice is to assign at least first value...

2024-11-03 03:11 UTC, akashkollipara commented on src/common/main.c
> +    RV32_ASSERT_GOTO(err, exit);
not all should goto exit...
it should to point to relevant deinit.

use pre_exit, exit, post_exit maybe?

2024-11-03 03:11 UTC, akashkollipara commented on src/opcode/rv32_fetch_decode.c
> +    "pc",
use real reg names instead of canonical names. or atleast create alias (macros or #defines).
btw... canonical name for `x0` is `zero`

2024-11-03 03:11 UTC, akashkollipara commented on src/opcode/rv32_fetch_decode.c
> +    "minstret",
this might not be the right way to proceed as these registers do have non sequential addresses.

2024-11-03 03:11 UTC, akashkollipara commented on src/opcode/rv32_fetch_decode.c
> +    "minstret",
therefore by extension you might keep modifying this list. think of some alter approach. if the change is too big, let go and target it in upcoming release.

2024-11-05 16:40 UTC, pranjalchanda08 commented on Makefile
> +CC := gcc
this does not work
```sh
$ make
ccache gcc -Iinc/common -Iinc/tools -Iinc/device -Iinc/opcode -MMD -MP -g -c src/common/main.c -o build/src/common/main.c.o
make: ccache: Command not found
make: *** [Makefile:43: build/src/common/main.c.o] Error 127
```

2024-11-05 16:41 UTC, pranjalchanda08 commented on inc/common/main.h
> +#include "rv32i_execute.h"
updated

2024-11-05 17:01 UTC, pranjalchanda08 commented on src/opcode/rv32_fetch_decode.c
> +    "pc",
why shall we do that? These string are used to show the decoded instruction in the output. It is easier to read the alias names in that. One thing that can be done is to use the something like `r[n] <alias>` instead.

2024-11-05 17:03 UTC, pranjalchanda08 commented on src/opcode/rv32_fetch_decode.c
> +    "minstret",
we can revamp this. currently we can go ahead with the first release

2024-11-05 17:09 UTC, pranjalchanda08 commented on src/opcode/rv32_fetch_decode.c
> +    "pc",
```sh
-------------- Execution Start --------------
[22:38:35.003] [INFO ]: [0x00002117]: [PC:0x00001000]:  auipc   x2 <sp>   , 0x2000 <8192d>
[22:38:35.003] [INFO ]: [0x00010113]: [PC:0x00001004]:  addi    x2 <sp>   , x2 <sp>   , 0x00 <00d>
[22:38:35.003] [INFO ]: [0x01300293]: [PC:0x00001008]:  addi    x5 <t0>   , x0 <zero> , 0x13 <19d>
[22:38:35.003] [INFO ]: [0x02300313]: [PC:0x0000100C]:  addi    x6 <t1>   , x0 <zero> , 0x23 <35d>
[22:38:35.003] [INFO ]: [0x006283B3]: [PC:0x00001010]:  add     x7 <t2>   , x5 <t0>   , x6 <t1>   
[22:38:35.003] [INFO ]: [0x00001E97]: [PC:0x00001014]:  auipc   x29 <t4>  , 0x1000 <4096d>
[22:38:35.003] [INFO ]: [0xFECE8E93]: [PC:0x00001018]:  addi    x29 <t4>  , x29 <t4>  , 0xffffffec <-20d>
[22:38:35.003] [DEBUG]: PC reached EOF
-------------- Execution End ----------------
```

2024-11-06 09:15 UTC, pranjalchanda08 commented
Waiting for @shibcreate to complete her L0 test on multiple instructions then we can plan on the release including those changes

2024-11-13 12:28 UTC, akashkollipara commented on Makefile
> +GCC_MINOR := $(word 2, $(subst ., ,$(GCC_VERSION)))
I am not happy with this implementation. But as this is not a blocker, I will ignore it.

Please try to refactor this change.

2024-11-13 12:30 UTC, akashkollipara commented on Makefile
> +SRCS := $(shell find $(SRC_DIRS) -type f \( -name '*.cpp' -o -name '*.c' -o -name '*.s' \))
## Fix needed
Doing this can be risky.
Consider this case, where one wants to create a c file and its not ready for build. The build tree will break.

2024-11-13 12:32 UTC, akashkollipara commented on Makefile
> +
Instead add min_version for newer flags.
```
if(version > min_verion)
 flag = abc;
else
 flag = def;
```

2024-11-13 12:32 UTC, akashkollipara commented on Makefile
> +
Avoid hard coding.

2024-11-13 12:33 UTC, akashkollipara commented on Makefile
> +ARGS ?=
?= is used to assign if not assigned.

Alternatively dont use or assign a default value.

2024-11-13 12:33 UTC, akashkollipara commented on Makefile
> +.PHONY: run
phony is used when target doesnt exist and error will not be raised.

2024-11-13 12:35 UTC, akashkollipara commented on rv32_asm/and.s
> +	la sp, stack_top
@pranjalchanda08 are you not mandating gp reg update to start the code?

2024-11-13 12:36 UTC, akashkollipara requested changes
Please address the comments.

2024-11-13 15:40 UTC, pranjalchanda08 commented on rv32_asm/and.s
> +	la sp, stack_top
I am aware of this but currently GP init is not mandated. Shall be done once the exceptions are up.

2024-11-13 15:41 UTC, pranjalchanda08 commented on Makefile
> +GCC_MINOR := $(word 2, $(subst ., ,$(GCC_VERSION)))
I am closing all the Makefile related issue for now and creating a bug to fix it in next release.

2024-11-13 15:44 UTC, pranjalchanda08 commented on Makefile
> +ARGS ?=
The default value is supposed to be empty

2024-11-13 15:46 UTC, pranjalchanda08 commented
@akashkollipara, all the issues are listed in https://github.com/pranjalchanda08/slash-sim/issues/33
Please approve for the release. 
We can fix it all in the upcoming release builds

2024-11-13 15:49 UTC, akashkollipara approved these changes

2024-11-13 15:50 UTC, merged