Fr/4 add csr instruction and register support
pranjalchanda08/rv32i_ISA_emu pull request #25
Opened 2024-10-30 19:09 UTC by deveshshevde

csr reg dump + toolchain version independent

2024-11-03 03:13 UTC, akashkollipara commented
@deveshshevde it appears that you are not following git rebase strategy to keep your branch updated. This will always end up in conflicts.

Close this PR and raise a new one based on "rebase" strategy!

2024-11-03 03:16 UTC, akashkollipara requested changes

2024-11-03 03:16 UTC, akashkollipara commented on Makefile
> +endif
not a good way to proceed. use static assignment march_flag, usually they are backward compatible.

2024-11-03 03:16 UTC, akashkollipara commented on src/common/main.c
> +    }
@pranjalchanda08 @deveshshevde how do you plan to 64b support?

2024-11-03 07:19 UTC, deveshshevde commented on Makefile
> +endif
Oh ok will do

2024-11-03 16:26 UTC, akashkollipara commented
> @deveshshevde it appears that you are not following git rebase strategy to keep your branch updated. This will always end up in conflicts.
> 
> Close this PR and raise a new one based on "rebase" strategy!

Highlighting this ...

2024-11-05 16:34 UTC, pranjalchanda08 commented
Hi @deveshshevde Please solve the issue.

2024-11-07 16:41 UTC, pranjalchanda08 commented on Makefile
> +endif
The flag does not work for older compilers. We can proceed with this way for now

2024-11-07 16:42 UTC, pranjalchanda08 commented on src/common/main.c
> +    }
Currently we are focusing on rv32 only but shall revisit all the requirements and changes for RV64/128...

2024-11-07 17:27 UTC, closed without merging