Fix minor issues in Makefile for Release 0.1 (#33)
pranjalchanda08/rv32i_ISA_emu pull request #36
Opened 2024-11-27 17:40 UTC by Tabrez-dev

This PR addresses minor issues in the Makefile for Release 0.1, as mentioned in issue #33. 
This PR includes fixes for concerns raised in the issue except 2nd one:
1) Removed GCC major minor variables
3) Added min version for newer flags
4) Removed all Phony variables.

2024-11-27 17:54 UTC, pranjalchanda08 requested changes

2024-11-27 17:54 UTC, pranjalchanda08 commented on Makefile
> +#I dont know about you guys but my gcc version is 9.3.0 and i cant seem to go higher so I will get a warning
can you remove this comment

2024-11-27 17:54 UTC, pranjalchanda08 commented on Makefile
> +  $(warning Bad toolchain version $(GCC_VERSION). Minimum required: $(GCC_MIN_VERSION))
This shall be provided as **Recommended** not as a must. As we are still able to support the toolchain version.

2024-11-27 18:09 UTC, Tabrez-dev commented on Makefile
> +  $(warning Bad toolchain version $(GCC_VERSION). Minimum required: $(GCC_MIN_VERSION))
Should i remove this check? or change it like this:

# Compare normalized versions and issue a warning if the current version is lower than the minimum required version
ifeq ($(shell [ $(CURRENT_VERSION_NUMERIC) -lt $(MIN_VERSION_NUMERIC) ] && echo 1 || echo 0), 1)
	$(warning Bad toolchain version $(GCC_VERSION). Recommended: $(GCC_MIN_VERSION))
endif

2024-11-27 18:10 UTC, Tabrez-dev commented on Makefile
> +#I dont know about you guys but my gcc version is 9.3.0 and i cant seem to go higher so I will get a warning
Done

2024-12-02 19:47 UTC, pranjalchanda08 approved these changes

2024-12-02 19:47 UTC, pranjalchanda08 commented on Makefile
> +  $(warning Bad toolchain version $(GCC_VERSION). Minimum required: $(GCC_MIN_VERSION))
warning is ok

2024-12-18 07:06 UTC, pranjalchanda08 commented
Hi @Tabrez-dev is this PR part of #37 as well? If yes please close this

2024-12-18 08:02 UTC, closed without merging

2024-12-18 08:03 UTC, Tabrez-dev commented
Major make files fix branch fixed all the issues of #37