Major fix makefile, Fixes issue #33
pranjalchanda08/rv32i_ISA_emu pull request #37
Opened 2024-11-28 16:04 UTC by Tabrez-dev

Fixes all issues in #33 
This includes fixes in minor-fix-makefile.

1. Added Makefiles inside src directory and in its sub directories.
2. Added a Makefile in the rv32_asm directory to handle assembly build task.

2024-11-29 17:33 UTC, RahulGoyal-tech commented on Makefile
> +GCC_MIN_VERSION := 11.0.0
should we add a seperate config.mk to avoid hardcoding this in this makefile and providing a seperate file to configure this and other hardcoded variables like Target Executable name, build dir name, out directory name, ASM directory name if some user want to define them with some other name?

2024-12-02 19:47 UTC, pranjalchanda08 commented
@akashkollipara Please have a look on this

2024-12-03 00:42 UTC, Tabrez-dev commented on Makefile
> +GCC_MIN_VERSION := 11.0.0
is config.mk required? @akashkollipara

2024-12-03 04:34 UTC, akashkollipara commented on Makefile
> +GCC_MIN_VERSION := 11.0.0
No. Have at top/start of makefile.

2024-12-03 04:37 UTC, akashkollipara commented
@Tabrez-dev you are repeating the same pieces of recipe in build.mk files. try to have it top level makefile and only gather paths from build.mk

2024-12-03 04:37 UTC, akashkollipara requested changes
Simplify build.mk

2024-12-06 02:23 UTC, Tabrez-dev commented
> Simplify build.mk

@akashkollipara I've simplified the build.mk files to only gather source file paths. 
The compilation rules are now centralized in the top-level Makefile. Can you please check it?

2024-12-15 20:17 UTC, pranjalchanda08 commented
@akashkollipara please have a look

2024-12-17 07:24 UTC, akashkollipara approved these changes

2024-12-17 07:24 UTC, merged