Initial Commit
pranjalchanda08/rv32i_ISA_emu pull request #38
Opened 2024-12-02 10:49 UTC by RahulGoyal-tech

2024-12-06 13:47 UTC, pranjalchanda08 requested changes

2024-12-06 13:47 UTC, pranjalchanda08 commented on src/device/bus.c
> +        if (!((splash_dev_tree[i].mmio_base > bus_limit) || (splash_dev_tree[i].mmio_base == 0 && bus_limit == 0)))
What happens if the MMIO_BASE of any device does not start from 0x00?

2024-12-06 13:47 UTC, pranjalchanda08 commented on src/device/bus.c
> +volatile uint32_t bus_limit = 0;
rename bus_limit to bus_reg_max_addr.

2024-12-06 14:55 UTC, RahulGoyal-tech commented on src/device/bus.c
> +        if (!((splash_dev_tree[i].mmio_base > bus_limit) || (splash_dev_tree[i].mmio_base == 0 && bus_limit == 0)))
What this does is ensuring that mmio_base of any device is not starting from the memory range allocated to previous device (i.e. it should be after previous bus limit) and if bus limit = 0. then mmio base can be 0

Got it. So i got confused in mmio_stride. I thought it as end address instead of length. Will correct the logic here.

2024-12-06 15:13 UTC, RahulGoyal-tech commented
Removed below condition because by the architecture of the slash-sim, user cannot define a device with ending address lower than base address, as stride is length of a peripheral in bytes rather than the end address.
![image](https://github.com/user-attachments/assets/12090802-a9db-4142-876b-efffcdf522b1)

Updates Variable name

corrected logic so that bus max address is at mmio_base + mmio_stride.

2024-12-08 15:16 UTC, pranjalchanda08 approved these changes

2024-12-08 15:16 UTC, merged